<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="arifasha" name="Test1" tests="9" failures="2" timestamp="23 Apr 2018 20:21:32 GMT" time="0.109" errors="0">
  <testcase name="Test1" time="0.034" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="com.pwot.qa.iteration1.Practice">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.pwot.qa.iteration1.Practice.Test1(Practice.java:38)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.009" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.004" classname="com.pwot.qa.iteration1.Practice">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="com.pwot.qa.iteration1.Practice">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.pwot.qa.iteration1.Practice.Test2(Practice.java:43)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="com.pwot.qa.iteration1.Practice"/>
</testsuite> <!-- Test1 -->
